version: "3.8"
services:
  nginx-frontend:
    build:
      context: ./web-app
      dockerfile: Dockerfile
      args:
        REACT_APP_API_GATEWAY: ${REACT_APP_API_GATEWAY}
        REACT_APP_CLIENT_ID: ${REACT_APP_CLIENT_ID}
        REACT_APP_AUTH_REDIRECT_URL: ${REACT_APP_AUTH_REDIRECT_URL}
    image: nonono000/nginx-frontend:${VERSION}
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: api-gateway
    image: nonono000/api-gateway:${VERSION}
    depends_on:
      - identity-service
      - profile-service
      - file-service
      - chat-service
      - post-service
    networks:
      - app-network
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: identity-service
    image: nonono000/identity-service:${VERSION}
    networks:
      - app-network
      - kafka-net
    depends_on:
      - kafka
  post-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: post-service
    image: nonono000/post-service:${VERSION}
    networks:
      - app-network
  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: profile-service
    image: nonono000/profile-service:${VERSION}
    networks:
      - app-network

  file-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: file-service
    image: nonono000/file-service:${VERSION}
    networks:
      - app-network

  chat-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: chat-service
    image: nonono000/chat-service:${VERSION}
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    networks:
      - kafka-net

  kafka:
    image: bitnami/kafka:3.8.0
    container_name: kafka

    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    networks:
      - kafka-net

networks:
  app-network:
    external: true
  kafka-net:
    driver: bridge
