server:
  port: 8080
  servlet:
    context-path: /post
spring:
  application:
    name: post-service
  data:
    mongodb:
      uri: ${MONGO_URI_POST_SERVICE:mongodb://root:root@localhost:27017/post-service?authSource=admin}
app:
  services:
    profile:
      url: ${PROFILE_SERVICE_URL:http://localhost:8081/profile}
