server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:123456789}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  services:
    file-service: ${FILE_SERVICE_URL:http://localhost:8084/file}
    identity-service: ${IDENTITY_SERVICE_URL:http://localhost:8080/identity}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
