server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: ${NEO4J_URI:bolt://my-neo4j:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:123456789}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  services:
    file-service: ${FILE_SERVICE_URL:http://file-service:8080/file}
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
