server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  neo4j:
    uri: ${NEO4J_URI:bolt://localhost:7687}
    authentication:
      username: ${NEO4J_USERNAME:neo4j}
      password: ${NEO4J_PASSWORD:123456789}
app:
  services:
    file-service: ${FILE_SERVICE_URL:http://file-service:8080/file}
