server:
  port: 8080
  servlet:
    context-path: /admin

spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: ${MONGO_URI_ADMIN_SERVICE:mongodb://root:root@my-mongo:27017/admin-service?authSource=admin}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

app:
  services:
    identity: ${IDENTITY_SERVICE_URL:http://identity-service:8080/identity}
    post: ${POST_SERVICE_URL:http://post-service:8080/post}
  jwt:
    cookie-name: ADMIN_TOKEN

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
feign:
  httpclient:
    hc5:
      enabled: true