name: CI/CD Microservices

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Identity Service
        run: |
          cd identity-service
          mvn clean package -DskipTests
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-service .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/identity-service
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/identity-service:latest
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name identity-service --env-file .env ${{ secrets.DOCKER_USERNAME }}/identity-service:latest