name: CI/CD Microservices

on:
  push:
    branches:
      - deploy-to-ec2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Identity Service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/identity-service -f identity-service/Dockerfile .
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/identity-service
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Copy .env
        run: cp /home/ubuntu/.env ./.env
      - name: Stop existing container if running
        run: |
          if [ $(docker ps -q -f name=identity-service) ]; then
          docker stop identity-service
          docker rm identity-service
          fi
      - name: Pull Image from docker hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/identity-service:latest
      - name: Run docker container
        run: |
          docker run -d \
            --name identity-service \
            --network app-network \
            -p 8082:8080 \
            --env-file .env \
            -e SPRING_PROFILES_ACTIVE=docker \
            ${{ secrets.DOCKER_USERNAME }}/identity-service:latest
          
          docker network connect kafka-net identity-service
